# Generated by Django 4.1.2 on 2022-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articeles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('date', models.DateField(max_length=10, verbose_name='Date pubcication')),
            ],
        ),
    ]
